name: alexaquery_dart
description: A Dart library for querying Alexa devices.
version: 1.2.1
repository: https://github.com/smartclock-app/alexaquery-dart

environment:
  sdk: ^3.4.3

dependencies:
  dio: ^5.5.0+1
  path_provider: ^2.1.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
