name: alexaquery_dart
description: A Dart library for querying Alexa devices.
version: 3.0.3
repository: https://github.com/smartclock-app/alexaquery-dart

environment:
  sdk: ^3.4.3

dependencies:
  dio: ^5.5.0+1
  mutex: ^3.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
